DROP TABLE IF EXISTS BooksAuthors;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Publishers;
DROP TABLE IF EXISTS Authors;

CREATE TABLE Publishers (
	Id INT PRIMARY KEY IDENTITY (1,1),
	Name NVARCHAR (50) NULL
);

CREATE TABLE Authors (
	Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	FirstName NVARCHAR (50) NULL,
	LastName NVARCHAR (50) NULL,
	Bio NVARCHAR (250) NULL,
)

CREATE TABLE Books (
	Id INT PRIMARY KEY IDENTITY (1,1),
	Title NVARCHAR (50) NULL,
	Year INT NULL,
	ISBN NVARCHAR (50) NOT NULL UNIQUE,
	Summary NVARCHAR (250) NULL,
	Image NVARCHAR (50) NULL,
	Price DECIMAL (18,2) NULL,
	AuthorId INT Null,
	PublisherId INT Null,
	CONSTRAINT FK_Book_AuthorId FOREIGN KEY (AuthorId) REFERENCES Authors(Id),
	CONSTRAINT FK_Book_PublisherId FOREIGN KEY (PublisherId) REFERENCES Publishers(Id)
);

CREATE TABLE AuthorBooks (
	Id INT PRIMARY KEY IDENTITY (1,1),
	BookId INT,
	AuthorId INT,
	CONSTRAINT FK_AuthorBooks_BookId FOREIGN KEY (BookId) REFERENCES Books(Id),
	CONSTRAINT FK_AuthorBooks_AuthorId FOREIGN KEY (AuthorId) REFERENCES Authors(Id)
);
